### ISSUE TITLE
Inconsistency of unique field name (per page) and loading input data

### ISSUE THREAD

**Issue by dkastl** [pdfme/pdfme#490] opened 2024-06-27 09:55 UTC
### Describe the bug

While field names must be unique and an error is shown (and the schema JSON is invalid) when two or more fields have the same name, this is not the case when two fields of the same name are on different pages.

This causes problems, when `inputs` data is provided, because the `inputs` array doesn't seem to support multiple pages (despite the data passed as an object).

### To Reproduce

This two-page template schema works but has identically field names in each page:

```json
{
  "schemas": [{
    "field1": {
      "type": "text",
      "content": "Field 1 / Page 1",
      "position": {
        "x": 80.0,
        "y": 70.0
      },
      "width":45,
      "height":10
    },
    "field2": {
      "type": "text",
      "content": "Field 2 / Page 1",
      "position": {
        "x": 80.0,
        "y": 90.0
      },
      "width":45,
      "height":10
    }
  },{
    "field1": {
      "type": "text",
      "content": "Field 1 / Page 2",
      "position": {
        "x": 80.0,
        "y": 70.0
      },
      "width":45,
      "height":10
    },
    "field2": {
      "type": "text",
      "content": "Field 2 / Page 2",
      "position": {
        "x": 80.0,
        "y": 90.0
      },
      "width":45,
      "height":10
    }
  }],
  ...
}
```

But the following `inputs` will not work as expected:

```javascript
const inputs = [{ 
  field1: 'a1', 
  field2: 'b1'
},{
  field1: 'c1',
  field2: 'd1'
}];
```

At the moment only the following is supported, which does not work if the fields are not unique across pages:

```javascript
const inputs = [{ 
  field1: 'a1', 
  field2: 'b1'
}];
```

#### Option 1:

Fields should have a unique name through all pages of a multi-page PDF.

#### Options 2:

Support multiple pages for `inputs`:

```javascript
const inputs = [{ 
  field1: 'a1', 
  field2: 'b1'
},{
  field1: 'c1',
  field2: 'd1'
}];
```

### Your Environment

```markdown
- pdfme package(@pdfme/generator or @pdfme/ui): 4.0.2
- pdfme version: 4.0.2
- Operating system: Linux
- Node.js version or Browser name & version: Chrome 126.0.6478.126
```

### Your Error Log

```shell
No errors
```

### Additional context

Here is a two-page PDF template example:

[two_pages_template.json](https://github.com/user-attachments/files/16011591/two_pages_template.json)

**Comment by peteward** [comment] 2024-07-13 11:01
it would probably be easier to enforce uniqueness across multiple pages.

**Comment by hand-dot** [comment] 2024-07-18 00:40
I see. Currently, we can only provide UI feedback on unique constraints within the same page.   
We should make it so that users can understand unique constraints that span multiple pages.

![CleanShot 2024-07-18 at 09 39 02](https://github.com/user-attachments/assets/7a608ed2-9cde-4f47-953e-eb61d74d0814)

**Comment by dkastl** [comment] 2024-07-18 02:06
Thanks for the comments!

I'm actually not sure what would be the best (or most understandable) solution. There could be even cases where identical field keys could be convenient, for example when fields should appear on multiple pages. Then the input value only had to be provided once.

What I found most confusing currently is, that inputs need to be provided as array, similar to schemas, but input currently does not support something like "pages". If fields had to be unique across multiple pages the following would be enough:

```javascript
const inputs = { 
  field1: 'a1', 
  field2: 'b1',
  ...
};

**Comment by hand-dot** [comment] 2024-07-19 02:58
@dkastl 
I understand why you might feel confused.

The array in template.schemas represents the pages of the template.
The array in inputs represents the input for the template.

And PDF generation always produces a single PDF data.

There are historical reasons why inputs is Array.
The original library called [labelmake](https://github.com/hand-dot/labelmake), which pdfme is based on, was originally created for variable printing, and was designed to output multiple input sets as a single PDF data.

**Comment by Carloobando96** [comment] 2024-07-26 15:36
@dkastl @hand-dot  I have the same problem, I would expect the inputs to be generated per page but only a single array is generated instead of one per page like schemas.

**Comment by Carloobando96** [comment] 2024-07-26 22:25
> @dkastl @hand-dot I have the same problem, I would expect the inputs to be generated per page but only a single array is generated instead of one per page like schemas.

The error is generated in form mode and viewer, not in designer

**Comment by peteward** [comment] 2024-08-08 05:28
I can pick this up.

My approach will be that schemas are still assigned to a page, and inputs are still passed global, but we enforce uniqueness of the naming of schemas - both when they are created and validating when they are changed.

**Comment by dkastl** [comment] 2024-08-08 09:55
I am not fully familiar with how field names are used internally in the PDFme library, but I have a suggestion regarding the use of unique field IDs.

What if we implement unique field IDs (such as UUIDs) that users cannot set themselves in the designer? These IDs would guarantee uniqueness for each field.

Users could then set the field names as they wish, without worrying about name conflicts. This approach would be especially useful in scenarios where the same field name is needed multiple times, such as in page headers. In these cases, the `inputs` could provide the value for the field that is used in multiple places, removing the need to ensure unique field names.

**Comment by peteward** [comment] 2024-08-08 15:24
Internally in the designer the schemas do have an `id` which is a UUID for these purposes.

> Users could then set the field names as they wish, without worrying about name conflicts. This approach would be especially useful in scenarios where the same field name is needed multiple times, such as in page headers. In these cases, the inputs could provide the value for the field that is used in multiple places, removing the need to ensure unique field names.

How would this work with UUIDs? If you have an input that you wanted to use in 3 different places would you have to provide that same input 3 times? Or a single input and just match it input against all fields that match this `name`?

**Comment by dkastl** [comment] 2024-08-08 15:49
> How would this work with UUIDs? If you have an input that you wanted to use in 3 different places would you have to provide that same input 3 times? Or a single input and just match it input against all fields that match this name?

I didn't know that there are already UUIDs internally. Does this mean, that "field name" is only needed to match inputs for example?

Yes, I thought that if field names didn't need to be unique and could appear more than one times, then the value provided in `inputs` once would be applied to all appearances of a form field with that name.

If field names don't need to be unique, eventially even accross multiple pages, checking for unique field names would not be necessary and copying of fields didn't have to change the field name.

Another example could be a currency field, which could appear multiple times on an invoice template. This field could be set only once through `inputs`.

**Comment by peteward** [comment] 2024-08-08 16:16
OK, I understand.

At the moment the `id` (UUID field) is not persisted with the schema and instead we use the `name` or `key` as it's called and it's the index within the object.

So this would mean changing from:

```
[
  field1: {
    ...
  },
  field2: {
     ...
  },
]
```

to something quite different... 😄 you could index in the UUID or just have an array of schema.

Either way this would be a very big breaking change throughout pdfme. I don't think it's a bad idea but the implications are major.

In the meantime though at least we can reduce the chance of user error through the UI.

**Comment by dkastl** [comment] 2024-08-09 09:25
> Either way this would be a very big breaking change throughout pdfme. I don't think it's a bad idea but the implications are major.

Well, since I'm not too familiar with the library internals, this might be the case. If there is a more simple improvement that only affects UI, that's great. 
I just felt, that using field names as unique keys, that users can specify in the UI with all possible values like spaces, special characters, etc., can be cause a lot of work within the library. But I agree that such a change is not a pressing issue.

**Comment by peteward** [comment] 2024-08-10 06:14
I think for just using the Designer and Generator it's really cool to have reusable input values.

However, if you are using the Form view it breaks the UI, because each field has it's own input. e.g. if you had a `product_price` that you wanted to reuse in 3 places:

![Screenshot 2024-08-10 at 07 12 51](https://github.com/user-attachments/assets/034d1e5e-0757-43e9-a961-aa37f647ed68)

You would need to re-think the UI.

**Comment by hand-dot** [comment] 2024-11-14 12:24
@peteward can we close this issue?

**Comment by peteward** [comment] 2024-11-14 16:00
Yeah I think we can close it

**Closed by peteward** 2024-11-14 16:00 UTC
Labels: bug
